### ISSUE TITLE
uninstall SAP HANA

### ISSUE THREAD

**Issue by alexxa** [redhat-sap/sap-hana-deployment#24]
As a user, I would appreciate an option to remove all configuration for HANA and uninstall it.

If this option exists, add it to Readme, please.

**Comment by makentenza** [comment]
@alexxa we have been discussing the topic and there are a few reasons why we are not adding this:

- There is not much demand from customers. Migration and new deployments are the most common operations. Uninstall is not a topic with demand and customers are just decommissioning instances or reinstalling from scratch. 

- SAP Systems configuration after deployment is very opinionated. If will be very difficult to develop an automated uninstallation process that could cover all the different use cases and options. This process is not just about running the uninstall option for HANA or NetWeaver, but removing users, packages, configurations, mount points, shared devices, etc...

Hope it makes sense for you as well. In any case, we'll be happy to discuss this further with you over Slack if required.

**Comment by alexxa** [comment]
Thanks for all the details @makentenza . It makes sense. Feel free to close it.
