### ISSUE TITLE
LSS isnt supported in production enviornments

### ISSUE THREAD

**Issue by tbludau** [redhat-sap/sap-hana-deployment#5]
Hey,

i saw that the lss isnt supported in production enviornments. 

The local secure store (LSS) is currently released only for non-production single-host single-tenant scenarios.

https://help.sap.com/viewer/b3ee5778bc2e4a089d3299b82ec762a7/2.0.04/en-US/5a43dc48190f4543b0d840952d3dec55.html

Is it necessary that this parameter is marked as required?

**Comment by makentenza** [comment]
Hey @tbludau you are completely right, this is a typo in the README file. I'm working on a PR already to normalize the variable names for the role and will include a fix for this.
